### ISSUE TITLE
Expected a color. Got: transparent 

### ISSUE THREAD

**Issue by aaronjensen** [mjonuschat/bootstrap-sass-rails#1]
Likely due to using compass and bootstrap... is this not supported?

```
bootstrap-sass-rails (2.0.0.0) vendor/assets/stylesheets/twitter/bootstrap/_mixins.scss:456:in `gradient-striped'
bootstrap-sass-rails (2.0.0.0) vendor/assets/stylesheets/twitter/bootstrap/_progress-bars.scss:57
bootstrap-sass-rails (2.0.0.0) vendor/assets/stylesheets/twitter/bootstrap.css.scss:56
compass (0.12.alpha.4) lib/compass/sass_extensions/functions/gradient_support.rb:12:in `initialize'
compass (0.12.alpha.4) lib/compass/sass_extensions/functions/gradient_support.rb:236:in `new'
compass (0.12.alpha.4) lib/compass/sass_extensions/functions/gradient_support.rb:236:in `block in color_stops'
compass (0.12.alpha.4) lib/compass/sass_extensions/functions/gradient_support.rb:229:in `map'
compass (0.12.alpha.4) lib/compass/sass_extensions/functions/gradient_support.rb:229:in `color_stops'
compass (0.12.alpha.4) lib/compass/sass_extensions/functions/gradient_support.rb:285:in `linear_gradient'
sass (3.1.12) lib/sass/script/funcall.rb:88:in `_perform'
sass (3.1.12) lib/sass/script/node.rb:40:in `perform'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:216:in `visit_prop'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:201:in `block (2 levels) in visit_mixin'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:201:in `map'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:201:in `block in visit_mixin'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:39:in `with_environment'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:201:in `visit_mixin'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `map'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:39:in `with_environment'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:26:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `block in visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:236:in `visit_rule'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:146:in `block in visit_import'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:146:in `map'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:146:in `visit_import'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:146:in `block in visit_import'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:146:in `map'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:146:in `visit_import'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `map'
sass (3.1.12) lib/sass/tree/visitors/base.rb:53:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:39:in `with_environment'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:26:in `visit_children'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `block in visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:47:in `visit_root'
sass (3.1.12) lib/sass/tree/visitors/base.rb:37:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:18:in `visit'
sass (3.1.12) lib/sass/tree/visitors/perform.rb:7:in `visit'
sass (3.1.12) lib/sass/tree/root_node.rb:20:in `render'
sass (3.1.12) lib/sass/engine.rb:300:in `_render'
sass (3.1.12) lib/sass/engine.rb:247:in `render'
```

**Comment by mjonuschat** [comment]
This is due to chriseppstein/compass#356 - i've incorporated the workaround mentioned there.
